Feature/customer orders food
TofuBytes-Studies-Group/Ordering pull request #9
Opened 2024-11-20 14:55 UTC by solskinIsak

2024-11-25 14:23 UTC, HelenaLykstoft reviewed
LGTM, godt med tests der dækker det meste

2024-11-25 15:03 UTC, thejamiegc requested changes
Jeg ville nok gerne se du laver noget refactor på din controller. Og så kigget på test igen måske kig på hvordan vi andre har gjort dem.

2024-12-02 14:52 UTC, HelenaLykstoft reviewed
LGTM, men måske lige enten indkommenter eller slet de tests der er udkommenteret :D 

 - det stod i mine commits at man sku ignorere de udkommenterede tests x) -Isak

2024-12-02 15:08 UTC, thejamiegc requested changes
All most there kid you got some good looking now. but still some minor shit in there. so try again. 

ps. maybe just think the first time then i don't review such god awful code. ❤️

2024-12-02 15:08 UTC, thejamiegc commented on Ordering.IntegrationTests/OrderTests.cs
> +/*using Microsoft.AspNetCore.Mvc;
maybe delete this?

2024-12-02 15:08 UTC, thejamiegc commented on Ordering.UnitTests/Services/KafkaProducerServiceTest.cs
> +        kafkaProducer.Verify(x => x.ProduceAsync("order.accepted", $"{order.CustomerUserName}", It.Is<Order>(o => o.CustomerUserName == "Ikit Kugelblitz")), Times.Once);
```suggestion
        kafkaProducer.Verify(x => x.ProduceAsync("order.accepted", order.CustomerUserName, It.Is<Order>(o => o.CustomerUserName == "Ikit Kugelblitz")), Times.Once);
```

2024-12-02 15:08 UTC, thejamiegc commented on qodana.yaml
> +#-------------------------------------------------------------------------------#
skal denne file med?

2024-12-04 11:05 UTC, thejamiegc approved these changes
fine i will approve then

2024-12-04 11:07 UTC, merged